name: Release APK Builder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: JDK 8 Setup
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"

      - name: Grant rights
        run: chmod +x ./gradlew

      - name: Before build project
        run: echo sdk.dir $ANDROID_HOME > local.properties

      - name: Build project
        run: ./gradlew --no-daemon build

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: List Build APKs
        run: ls -al play-services-core/build/outputs/apk

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 'MicroG'
          path: play-services-core/build/outputs/apk/withMapboxWithoutNearby/release/play-services-core-withMapbox-withoutNearby-release-unsigned.apk
